# Generated by Django 4.1.3 on 2022-11-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bravo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('alpha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bravo', to='core.alpha')),
            ],
        ),
        migrations.CreateModel(
            name='Charlie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('bravo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charlie', to='core.bravo')),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('alpha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delta', to='core.alpha')),
                ('charlie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delta', to='core.charlie')),
            ],
        ),
        migrations.CreateModel(
            name='Foxtrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('delta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foxtrot', to='core.delta')),
            ],
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('delta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echoes', to='core.delta')),
            ],
        ),
    ]
